# Generated by Django 4.0.2 on 2022-02-06 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_f_name_alter_member_l_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='f_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z ]+$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='l_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[A-Za-z ]+$')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{3}-?\\d{3}-?\\d{4}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin - Can delete members'), ('Regular', "Regular - Can't delete members")], default='Regular', max_length=7, verbose_name='Role'),
        ),
    ]
